package:
  name: ovito
  version: "2.8.2"

source:
  path: ../../../
#  git_url: https://gitlab.com/stuko/ovito.git

requirements:
  build:
    - cmake
    - boost
    - git
    - netcdf4
    - hdf5
    - qt
    - zlib
    - python
    - numpy
    - pyqt
    - setuptools

  run:
    - netcdf4
    - hdf5
    - qt
    - zlib
    - python
    - numpy
    - pyqt

test:
  imports:
    - ovito

about:
  home: http://www.ovito.org
  license: GPLv3
  license_file: LICENSE.txt
  summary: "A scientific data visualization and analysis software for atomistic and other particle-based simulation models"